# Generated by Django 4.2 on 2024-03-02 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicinesName', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(blank=True, default='meidicine.png', null=True, upload_to='')),
                ('Quantity', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('Price', models.IntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
